#!/usr/bin/env ruby
$LOAD_PATH << File.expand_path('../../scripts',__FILE__)

require 'deployer/deployer'

STAGING_APP_NAME='tee-dub-labs---staging'
PROD_APP_NAME='tee-dub-labs'

unless ENV['HEROKU_API_KEY']
  puts "No heroku api key in the environment. I can't deploy without it, so I'm bailing out now"
  exit 0
end


case ENV['TRAVIS_BRANCH']
when 'master'
  Deployer::Deployer.deploy( STAGING_APP_NAME )
when 'prod_release_ptr'
  Deployer::Deployer.deploy( PROD_APP_NAME )
else
  puts "unrecognized branch name: '#{ENV['TRAVIS_BRANCH']}'. Not doing anything."
end

